{% set version = "3.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smoothwin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SmoothWin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SmoothWin/SmoothWin_{{ version }}.tar.gz
  sha256: c668284e087a59030bab0f61544d87a121b4ff5a8f13a172864367c201d6027f

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-nlme
  run:
    - r-base
    - r-nlme

test:
  commands:
    - $R -e "library('SmoothWin')"           # [not win]
    - "\"%R%\" -e \"library('SmoothWin')\""  # [win]

about:
  home: http://hamedhaseli.webs.com
  license: LGPL (>= 2)
  summary: The main function in the package utilizes a windowing function in the form of an exponential
    weighting function to linear models. The bandwidth and sharpness of the window are
    controlled by two parameters. Then, a series of tests are used to identify the right
    parameters of the window (see Charles Kervrann (2004) <doi:10.1007/978-3-540-24672-5_11>).
  license_family: LGPL

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast

# Package: SmoothWin
# Type: Package
# Version: 2.0.0
# Date: 2018-07-16
# Author: Hamed Haselimashhadi <hamedhm@ebi.ac.uk>
# Maintainer: Hamed Haselimashhadi <hamedhm@ebi.ac.uk>
# Depends: R (>= 2.0)
# Description: The main function in the package utilizes a windowing function in the form of an exponential weighting function to linear models. The bandwidth and sharpness of the window are controlled by two parameters. Then, a series of tests are used to identify the right parameters of the window (see Charles Kervrann (2004) <doi:10.1007/978-3-540-24672-5_11>).
# Title: Soft Windowing on Linear Regression
# License: LGPL (>= 2)
# Packaged: 2018-07-16 10:24:08 UTC; hamedhm
# Imports: nlme
# URL: http://hamedhaseli.webs.com
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-07-18 12:40:05 UTC
