{% set version = '3.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smoothwin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SmoothWin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SmoothWin/SmoothWin_{{ version }}.tar.gz
  sha256: c668284e087a59030bab0f61544d87a121b4ff5a8f13a172864367c201d6027f

build:
  merge_build_host: True  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rfast
    - r-nlme
  run:
    - r-base
    - r-rfast
    - r-nlme

test:
  commands:
    - $R -e "library('SmoothWin')"           # [not win]
    - "\"%R%\" -e \"library('SmoothWin')\""  # [win]

about:
  home: http://hamedhaseli.webs.com, https://www.mousephenotype.org/
  license: LGPL-2
  summary: The main function in the package utilizes a windowing function in the form of an exponential
    weighting function to linear models. The bandwidth and sharpness of the window are
    controlled by two parameters. Then, a series of tests are used to identify the right
    parameters of the window (see Hamed Haselimashhadi et al (2019) <https://www.biorxiv.org/content/10.1101/656678v1>).
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: SmoothWin
# Type: Package
# Version: 3.0.0
# Date: 2019-07-26
# Author: Hamed Haselimashhadi <hamedhm@ebi.ac.uk>
# Maintainer: Hamed Haselimashhadi <hamedhm@ebi.ac.uk>
# Depends: R (>= 3.5)
# Description: The main function in the package utilizes a windowing function in the form of an exponential weighting function to linear models. The bandwidth and sharpness of the window are controlled by two parameters. Then, a series of tests are used to identify the right parameters of the window (see Hamed Haselimashhadi et al (2019) <https://www.biorxiv.org/content/10.1101/656678v1>).
# Title: Soft Windowing on Linear Regression
# License: LGPL (>= 2)
# Packaged: 2019-07-27 18:35:10 UTC; My
# Imports: nlme, Rfast
# URL: http://hamedhaseli.webs.com, https://www.mousephenotype.org/
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2019-07-27 21:40:10 UTC
