appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: W9/wH8h0mWW0RfSHiHXRE2w5+BMqHa+tCig/TaWSvpIWXLonYFNB9M2Ayy5nP0hsooA+TTvHob/r6SoWgXTK5HLhI3k+S/cS6xojpYFhlw362ZCofMLDvjQ14VYuBDWg9znBb1FWCnqCuW3nUd3dY2uLR/NnwTEIW9XjbUyp7fPBWexeWtJXMfZnABdFdQ5lWYBvLF3Xo5wcOd44o4qmFOV92Ofdh9m2YTSqyFEWijYrex6D7Pmq6Q3rwIoiPmgDA2sQWBVd5sFp+Pf1Za9ZMGaWxGwc0nN8eWkc0sHX+MtEqtf7D2sCXpE0eFi8qqbCs4f9fnXBXu4MKoimfXU9GWS9J5gyh9nCJOGaX7bynzluN0FsVTBJqitX/FH4u8m3+E8PUnJ9D9crDxT8nQXoxEDsd3nKkvMxOQOE7JbjWfh+kMzWdahLrPvjlSYujuLROE7WObh5JkNUBloOiS0zU+tVpt6/MgLTga5gqnnyOahO+ZopVEs8qhPRDwyx4oFS8ZkmVHez3nB+y0ZQ0BPsULfwzMwiSGYURzYvpZxjEWoTfXbI7Zlxo0vNqDHelQx1W2keDaxuurwxmczjOTej3XB83Q2a2ZybZmU54cmAUYa2R44Y8qlxD+QUwgyun/WlAYf1JphofAv9HnkbtQTWYJ1unqnCmXPGSMKyW48zano=}
